### ISSUE TITLE
Trouble with Link to Clone Hero menu - unknown version

### ISSUE THREAD

**Issue by NickBonet** [sanjay900/guitar-configurator#2]
I'm having an issue with the "Link to Clone Hero" menu, I've pointed to my game install directory in the menu, but it still reports unknown version and thus can't launch from there/have my APA102 LEDs switch to star power/open note mode. 

![image](https://user-images.githubusercontent.com/521289/110422387-4279c800-806d-11eb-98b7-a4b2f6b78b57.png)

I'm running v8.0,2 which was released a few days ago.

**Comment by NickBonet** [comment]
My Clone Hero directory: 
![image](https://user-images.githubusercontent.com/521289/110422459-689f6800-806d-11eb-8dfe-8d12e7de45de.png)

**Comment by sanjay900** [comment]
What version of the game are you using?

**Comment by sanjay900** [comment]
ah yeah, its been a while since ive had the time to update the LED bindings, ill try and get to doing that this weekend

**Comment by NickBonet** [comment]
Ah that makes sense then, thanks!

**Comment by sanjay900** [comment]
Should be fixed with https://github.com/sanjay900/guitar-configurator/commit/bc2884599a06bb2338524abd8dff9a70db9b8cb5
turns out i did implement that version, but the files i was grabbing from the clone hero site to detect versions just was wrong for windows and that broke things. Ive changed it so you can just pick a version now instead of it trying to detect.
https://github.com/sanjay900/guitar-configurator/releases/tag/preview
