### ISSUE TITLE
Question: Does PS3 direct input poll faster than xinput?

### ISSUE THREAD

**Issue by inst34d** [sanjay900/guitar-configurator#61]
I've been doing several tests with different direct input modes and i'm pretty sure that PS3 direct input just feels faster (its even noticeable on the menu when moving up and down with the strum bar). Could someone with better ways of testing confirm this?

Also since last version (CH 1.0 and guitar configurator 9.1.2) the tilt sensor is just not working in game, but it does in the menu and it only works ingame when binding it to the select button, this happens with both modes PS3 and xInput, Im using a single sw520D sensor (configured as digital). 

### Version

yes

### What operating system are you using?

Windows 10

### os-other

Windows 10 LTSC

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
In the game you have that controller poll rate setting. That only gets used for XInput, as with XInput the game has to poll the controller manually, while with PS3 mode, the game gets fed inputs as they happen. 

A bunch of guys have switched to PS3 mode due to this, as it means you can still get 1000hz without turning that setting up, which is good as turning up that setting uses more cpu.

Interesting note about CH 1.0, i am not surprised about tilt not working for PS3 mode as there is some stuff im working on for that, but XInput breaking is quite odd. Does the rotation axis move at all when you tilt the guitar and view the controller outputs with the windows controller tester?

**Comment by inst34d** [comment]
That explains a lot, thanks a lot for your work. About the tilt, I really don't know what happened, it used to work fine when I first setup the guitar in xInput mode but after switching configurations with several modes it just broke ingame. It is really weird because the sensor works outside of the game, and also on the calibration menu ingame, I tried moving the zero, adding deadzone, invert, I can clearly see it go from 0 to 1 when I tilt it but it just doesn't trigger the star power ingame. The only solution was to bind the tilt sensor to the select button in the guitar configurator and just use it like that, the only downside is the occasional reset when on practice mode, but it's not a big deal.
